from typing import Self, overload

class MongoDB:
    def __init__(self, connection: str) -> None: ...
    def __new__(self, *args, **kwargs) -> Self: ...

class SQLDatabase:
    def __init__(self) -> None: ...
    def __new__(self) -> Self: ...

class Database:
    def __init__(self, connection: str | None = None): ...
    @overload
    def __new__(cls) -> SQLDatabase: ...
    @overload
    def __new__(cls, connection: str | None = None) -> MongoDB: ...
